export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS';
export const LOG_IN_ERROR = 'LOG_IN_ERROR';

export const SEARCH_ERROR = 'SEARCH_ERROR';
export const SET_SEARCH_TERM = 'SET_SEARCH_TERM';

export const GET_FEATURES = 'GET_FEATURES';
export const GET_FEATURES_ERROR = 'GET_FEATURES_ERROR';


